### ISSUE TITLE
Check JAR file exists

### ISSUE THREAD

**Issue by stanislavstarcha** [Tubular/sparkly#25]
Would be good to have some extra checks and make sure a file exists and is readable when adding JAR files to the context definition. It may simplify debugging process, because right now the whole behavior is opaque.

An extra check could be to make sure a list of jars was actually loaded in spark.

**Comment by drudim** [comment]
Looks like it's implemented in Spark 2.x:
```
Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
: java.io.FileNotFoundException: File file:/tmp/custom.jar does not exist
	at org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileStatus(RawLocalFileSystem.java:616)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatusInternal(RawLocalFileSystem.java:829)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:606)
	at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:431)
	at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:337)
	at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:289)
	at org.apache.spark.deploy.yarn.Client.copyFileToRemote(Client.scala:339)
	at org.apache.spark.deploy.yarn.Client.org$apache$spark$deploy$yarn$Client$$distribute$1(Client.scala:458)
```
